// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRbC7xbC5VE6eEBWx8K1C_kutjgDJazMA',
    appId: '1:400921458015:web:9cccf92f9b2c429d6f32ea',
    messagingSenderId: '400921458015',
    projectId: 'snackads-b36c2',
    authDomain: 'snackads-b36c2.firebaseapp.com',
    storageBucket: 'snackads-b36c2.appspot.com',
    measurementId: 'G-NKTX3XLYN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtB4TLAbQFg-oLQCb7jLALatHVDYlRLg4',
    appId: '1:400921458015:android:ca76929cf4a134186f32ea',
    messagingSenderId: '400921458015',
    projectId: 'snackads-b36c2',
    storageBucket: 'snackads-b36c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIsEqwl0SxlQ-SoBjbmSPEe_ik4BaE9Hs',
    appId: '1:400921458015:ios:6c934daf374f90f66f32ea',
    messagingSenderId: '400921458015',
    projectId: 'snackads-b36c2',
    storageBucket: 'snackads-b36c2.appspot.com',
    iosBundleId: 'com.example.snackAds',
  );
}
